<a href="https://colab.research.google.com/github/KJR020/The-Data-Science-Course-2020-Complete-Data-Science-Bootcamp/blob/main/Section34_MultipleLinearRegeression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Multiple linear regression**

## Import the relevant libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the data

In [3]:
data = pd.read_csv('/content/drive/MyDrive/DataAnalysis_projects/Complete Data Science Training/213/1.02.Multiple-linear-regression.csv')
data.head()

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54
3  1685           3  2.74
4  1693           2  2.83

In [4]:
data.describe()

SAT  Rand 1,2,3        GPA
count    84.000000   84.000000  84.000000
mean   1845.273810    2.059524   3.330238
std     104.530661    0.855192   0.271617
min    1634.000000    1.000000   2.400000
25%    1772.000000    1.000000   3.190000
50%    1846.000000    2.000000   3.380000
75%    1934.000000    3.000000   3.502500
max    2050.000000    3.000000   3.810000

## **Create the multiple linear regression**
## Declare the dependent and independent variable

In [7]:
x = data[['SAT','Rand 1,2,3']]
y = data['GPA']

## Regression itself

In [ ]:
reg = LinearRegression()
reg.fit(x,y)

In [10]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [11]:
reg.intercept_

0.29603261264909486

## Calculating the R-squared

In [12]:
reg.score(x,y)

0.4066811952814283

## **Fomula for Adjusted R^2**
$$ R^2_{adj.} = 1-(1-R^2)\frac{n-1}{n-p-1} $$


In [13]:
x.shape

(84, 2)

In [15]:
r2 = reg.score(x,y)
n = x.shape[0]
p = x.shape[1]
adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)
adjusted_r2

0.3920313482513401

In [16]:
from sklearn.feature_selection import f_regression

In [17]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [21]:
p_values = f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [22]:
p_values.round(3)

array([0.   , 0.676])

In [24]:
reg_summary = pd.DataFrame(data=x.columns.values,columns=['features'])
reg_summary

features
0         SAT
1  Rand 1,2,3

In [26]:
reg_summary['Coefficients'] = reg.coef_
reg_summary['p-values'] = p_values.round(3)

In [27]:
reg_summary

features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676